FROM python:3.12-bullseye
RUN apt update && \
    apt upgrade -y && \
    apt install -y sudo curl make
ENV SHELL bash
ARG USERNAME=node
RUN mkdir -p /scripts
RUN curl -o /scripts/setup_user.sh -fL https://raw.githubusercontent.com/itkmaingit/my-config/main/docker/setup_user.sh --silent
RUN bash /scripts/setup_user.sh $USERNAME

USER $USERNAME
WORKDIR /home/"$USERNAME"/works
COPY ./works /home/"$USERNAME"/works

RUN echo 'export PYTHONPATH=/home/node/works/puzzle_dsl_interpreter' >> /home/$USERNAME/.bashrc

RUN bash /home/$USERNAME/works/setup.sh $USERNAME
