from __future__ import annotations

from enum import IntEnum, auto


class RuleType(IntEnum):
    file = auto()
    structsDeclaration = auto()
    domainHiddenDeclaration = auto()
    constraintsDeclaration = auto()
    structID = auto()
    newStructID = auto()
    structDefinitionBody = auto()
    structDefinition = auto()
    structDefinitions = auto()
    relationshipID = auto()
    relationshipSetBody = auto()
    relationshipSet = auto()
    pID = auto()
    cID = auto()
    epID = auto()
    ecID = auto()
    intDomainValue = auto()
    rangeValue = auto()
    domainValue = auto()
    domainSetBody = auto()
    domainSet = auto()
    hiddenValue = auto()
    hiddenSetBody = auto()
    hiddenSet = auto()
    domainDefinitionBody = auto()
    pDefinition = auto()
    cDefinition = auto()
    epDefinition = auto()
    ecDefinition = auto()
    customStructDefinition = auto()
    domainDefinitions = auto()
    int = auto()
    primitiveValue = auto()
    set = auto()
    solutionFunction = auto()
    bFunction = auto()
    crossFunction = auto()
    cycleFunction = auto()
    allDifferentFunction = auto()
    isRectangleFunction = auto()
    isSquareFunction = auto()
    connectFunction = auto()
    noOverlapFunction = auto()
    fillFunction = auto()
    quantifier = auto()
    index = auto()
    quantifierIndex = auto()
    indexFunction = auto()
    structElement = auto()
    generationSet = auto()
    boolean = auto()
    singleBoolean = auto()
    notBoolean = auto()
    parenthesizedBoolean = auto()
    quantifierBoolean = auto()
    compoundBoolean = auto()
    constraint = auto()
    constraintDefinition = auto()
    constraintsDefinitions = auto()
